Test case signup_02
daniela11cuellar/FinalProjectApplaudo pull request #8
Opened 2022-10-22 03:16 UTC by daniela11cuellar

-Test Case SignUp_02
In this test case it was validated that when entering an existing email a user cannot create an account

2022-10-22 21:55 UTC, mgarciaapplaudo requested changes
These tests implement the antipattern of coupling tests together. As best practice, tests should always be able to be run independently from one another and still pass.

See [Cypress best practices](https://docs.cypress.io/guides/references/best-practices#Having-tests-rely-on-the-state-of-previous-tests)

2022-10-23 22:25 UTC, ccontrerasapplaudo submitted a review, later dismissed
The test case works as intended

2022-10-24 17:17 UTC, daniela11cuellar commented
@mgarciaapplaudo I had created sign up file with both test cases and I implemented your comment.

2022-10-25 02:36 UTC, ccontrerasapplaudo approved these changes

2022-10-25 21:18 UTC, mgarciaapplaudo approved these changes

2022-10-25 21:20 UTC, merged